# 실행 방법
# chmod +x generate-env-file.sh
# ./generate-env-file.sh

#!/bin/bash

#TARGET_DIR="/protector-infra/overlays/develop/backend/secret-workspace"
TARGET_FILE="/.env.secret"

cat > "$TARGET_FILE" <<EOF
MASTER_DB_CONNECTION=${MASTER_DB_CONNECTION}
MASTER_DB_NAME=${MASTER_DB_NAME}
SLAVE_DB_CONNECTION=${SLAVE_DB_CONNECTION}
SLAVE_DB_NAME=${SLAVE_DB_NAME}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
AI_DOMAIN=${AI_DOMAIN}
AI_PORT=${AI_PORT}
AI_RECOMMEND_PATH=${AI_RECOMMEND_PATH}
DB_PASSWORD=${DB_PASSWORD}
DB_USERNAME=${DB_USERNAME}
JWT_SECRET=${JWT_SECRET}
SENTRY_DSN=${SENTRY_DSN}
EOF

echo "env 파일이 $TARGET_FILE 에 생성되었습니다!"
