apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
  labels:
    app: backend-application

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: backend-application

  template:
    metadata:
      name: backend-application
      labels:
        app: backend-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"

    spec:
      containers:
        - name: backend-application
          image: han16935/protector-be
          imagePullPolicy: IfNotPresent
          ports:
            - name : http
              containerPort: 8080

          resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
              limits:
                cpu: "1000m"  # 최대 1 CPU 코어 제한
                memory: "512Mi"

          envFrom:
            - configMapRef:
                name: backend-configmap
      restartPolicy: Always

