apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
  labels:
    app: backend-application

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-application

  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      name: backend-application
      labels:
        app: backend-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"

    spec:
      containers:
        - name: backend-application
          image: ${backend_image}
          imagePullPolicy: IfNotPresent
          ports:
            - name : http
              containerPort: 8080

          resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
              limits:
                cpu: "1000m"  # 최대 1 CPU 코어 제한
                memory: "512Mi"

          envFrom:
            - configMapRef:
                name: backend-configmap
      restartPolicy: Always

