apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
    MASTER_DB_CONNECTION : "${MASTER_DB_CONNECTION}"
    MASTER_DB_NAME: "${MASTER_DB_NAME}"
    SLAVE_DB_CONNECTION: "${SLAVE_DB_CONNECTION}"
    SLAVE_DB_NAME: "${SLAVE_DB_NAME}"

    DB_USERNAME: "${DB_USERNAME}"

    REDIS_HOST: "${REDIS_HOST}"
    REDIS_PORT: "${REDIS_PORT}"

    SENTRY_DSN : "${SENTRY_DSN}"

    AI_DOMAIN: "${AI_DOMAIN}"
    AI_PORT: "${AI_PORT}"
    AI_RECOMMEND_PATH: "${AI_RECOMMEND_PATH}"



