apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backend
  - sealed-secret.yaml

patches:
  - path: patch-image.yaml
  - path: patch-env.yaml
  - path : patch-service.yaml

generatorOptions:
  disableNameSuffixHash: true
