apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
spec:
  template:
    spec:
      containers:
        - name: backend-application
          image: 637423458012.dkr.ecr.ap-northeast-2.amazonaws.com/home-protector:be039674777e3b04d51ea18408a59b9c68a045c4
