apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
spec:
  template:
    spec:
      containers:
        - name: backend-application
          image: 637423458012.dkr.ecr.ap-northeast-2.amazonaws.com/home-protector:05e39ff73ecc54b166429196b2984ac2d35e1fc6
