apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-application
  labels:
    app: ai-application

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-application

  template:
    metadata:
      name: ai-application
      labels:
        app: ai-application
      annotations:
        prometheus.io/scrape: "false"

    spec:
      containers:
        - name: ai-application
          image: han16935/protector-ai:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name : http
              containerPort: 5000
      restartPolicy: Always
